'use client';
import Link from 'next/link';
import {useActionState,useState} from 'react';
import {type Section,sections} from '@/lib/fields';
import {type ListState} from '@/lib/list-query';
import {searchRecords} from '@/lib/search-action';
import {dealStatuses,labels,formatDate,money} from '@/lib/domain';
export function RecordList({section,initial}:{section:Section;initial:ListState}){
 const [state,action,pending]=useActionState(searchRecords.bind(null,section),initial);
 const [filters,setFilters]=useState({q:'',status:'',view:'',sort:'updated_at'});
 const allowedSort=section==='customers'?['updated_at','created_at','last_name']:section==='tasks'?['updated_at','created_at','title','due_date']:['updated_at','created_at','title'];
 const pages=Math.max(1,Math.ceil(state.count/20));
 return <form action={action} aria-busy={pending}><fieldset disabled={pending}><div className="filters"><label>Suche<input name="q" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})} placeholder={section==='customers'?'Name oder E-Mail':'Titel'} maxLength={100}/></label>{section==='deals'&&<label>Status<select name="status" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Alle Status</option>{dealStatuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label>}{section==='tasks'&&<label>Ansicht<select name="view" value={filters.view} onChange={e=>setFilters({...filters,view:e.target.value})}>{[['','Offene Aufgaben'],['today','Heute'],['overdue','Überfällig'],['week','Diese Woche'],['later','Später'],['done','Erledigt / storniert']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}<label>Sortierung<select name="sort" value={filters.sort} onChange={e=>setFilters({...filters,sort:e.target.value})}>{allowedSort.map(s=><option key={s} value={s}>{{updated_at:'Letzte Aktivität',created_at:'Neueste zuerst',last_name:'Nachname A–Z',title:'Titel A–Z',due_date:'Fälligkeit'}[s]}</option>)}</select></label><button type="submit" name="page" value="1">{pending?'Wird geladen …':'Anwenden'}</button></div>
 {state.error&&<p className="alert error" role="alert">{state.error}</p>}
 {state.rows.length?<section className="panel table-panel"><table><thead><tr><th>{section==='customers'?'Name':'Titel'}</th><th>{section==='customers'?'Kontakt':'Status'}</th><th>{section==='customers'?'Vermittlungen':section==='deals'?'Betrag':'Fällig / Priorität'}</th><th>Letzte Aktivität</th></tr></thead><tbody>{state.rows.map(row=><tr key={row.id}><td data-label={section==='customers'?'Name':'Titel'}><Link href={`/portal/${section}/${row.id}`}>{section==='customers'?`${row.first_name} ${row.last_name}`:row.title}</Link>{section==='deals'&&<small>{row.deal_number}</small>}</td><td data-label={section==='customers'?'Kontakt':'Status'}>{section==='customers'?<>{row.email??'—'}<small>{row.phone??'—'}</small></>:<span className={`badge badge-${row.status}`}>{labels[row.status??'']}</span>}</td><td data-label={section==='customers'?'Vermittlungen':section==='deals'?'Betrag':'Fällig / Priorität'}>{section==='customers'?row.deals?.[0]?.count??0:section==='deals'?money(row.investment_amount??null):`${formatDate(row.due_date??null)} · ${labels[row.priority??'']}`}</td><td data-label="Letzte Aktivität">{formatDate(row.updated_at)}</td></tr>)}</tbody></table></section>:<div className="empty"><span className="empty-symbol" aria-hidden="true">◇</span><h2>{section==='tasks'?'Keine Aufgaben in dieser Ansicht':`Keine ${sections[section].title} in dieser Ansicht`}</h2><p className="muted">{section==='customers'?'Erstellen Sie Ihren ersten Kunden oder passen Sie die Suche an.':'Neue Einträge erscheinen hier, sobald Sie sie anlegen. Prüfen Sie gegebenenfalls die Filter.'}</p><Link className="button primary" href={`/portal/${section}/new`}>{sections[section].singular} anlegen →</Link></div>}
 <nav className="pagination" aria-label="Seitennavigation"><button name="page" value={state.page-1} disabled={state.page<=1||pending}>← Zurück</button><span role="status">Seite {state.page} von {pages} · {state.count} Einträge</span><button name="page" value={state.page+1} disabled={state.page>=pages||pending}>Weiter →</button></nav></fieldset></form>;
}
