import Link from '@/components/link';
import Image from 'next/image';
import type { ReactNode } from 'react';
import { labels,formatDate,type Task,type Deal } from '@/lib/domain';
import type { Field } from '@/lib/fields';
export function Brand(){return <Link href="/portal" className="brand" aria-label="Nexus Network Übersicht"><span className="logo-frame"><Image src="/nexus-brand.png" width={740} height={349} alt="" /></span><span>NEXUS<span className="brand-sub">NETWORK</span></span></Link>;}
export function Badge({value}:{value:string}){return <span className={`badge badge-${value}`}>{labels[value]??value}</span>;}
export function Heading({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:ReactNode}){return <header className="page-heading"><div><p className="eyebrow">{eyebrow??'NEXUS NETWORK / PARTNERPORTAL'}</p><h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>{children}</header>;}
export function Empty({title,children,href,label}:{title:string;children?:ReactNode;href?:string;label?:string}){return <div className="empty"><span className="empty-symbol" aria-hidden="true">◇</span><h2>{title}</h2><p className="muted">{children}</p>{href&&<Link className="button primary" href={href}>{label??'Jetzt anlegen'} →</Link>}</div>;}
export function FieldInput({field,value,choices=[]}:{field:Field;value?:string|number|null;choices?:{id:string;label:string}[]}){
  const props={name:field.name,id:field.name,required:field.required,defaultValue:value??'',maxLength:field.max??200};
  return <label className={field.type==='textarea'?'wide':''} htmlFor={field.name}>{field.label}{field.required?' *':''}{field.options?<select {...props}>{field.options.map(option=><option key={option} value={option}>{labels[option]??option}</option>)}</select>:['customer','deal','member'].includes(field.type??'')?<select {...props}><option value="">Bitte auswählen</option>{choices.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select>:field.type==='textarea'?<textarea {...props} rows={4}/>:<input {...props} type={field.type??'text'} min={field.type==='number'?0:undefined} step={field.type==='number'?'0.01':undefined}/> }</label>;
}
export function TaskList({tasks}:{tasks:Task[]}){return tasks.length?<ul className="record-list">{tasks.map(t=><li key={t.id}><Link href={`/portal/tasks/detail?id=${t.id}`}><strong>{t.title}</strong><span>{formatDate(t.due_date)} · {labels[t.priority]}</span></Link><Badge value={t.status}/></li>)}</ul>:<p className="muted">Keine Aufgaben in dieser Ansicht.</p>;}
export function DealList({deals}:{deals:Deal[]}){return deals.length?<ul className="record-list">{deals.map(d=><li key={d.id}><Link href={`/portal/deals/detail?id=${d.id}`}><strong>{d.title}</strong><span>{d.deal_number} · {formatDate(d.created_at)}</span></Link><Badge value={d.status}/></li>)}</ul>:<p className="muted">Noch keine Vermittlungen.</p>;}
export function Pagination({base,page,count,query}:{base:string;page:number;count:number;query?:Record<string,string>}){const pages=Math.max(1,Math.ceil(count/20));const href=(p:number)=>`${base}?${new URLSearchParams({...query,page:String(p)})}`;return <nav className="pagination" aria-label="Seitennavigation">{page>1?<Link href={href(page-1)}>← Zurück</Link>:<span/>}<span>Seite {page} von {pages} · {count} Einträge</span>{page<pages?<Link href={href(page+1)}>Weiter →</Link>:<span/>}</nav>;}
