'use client';
import Link from '@/components/link';
import {notFound} from '@/lib/navigation';
import {tenant} from '@/lib/access';
import {isSection,sections} from '@/lib/fields';
import {uuid} from '@/lib/validation';
import {addNote,completeTask} from '@/lib/actions';
import {formatDate,money,labels,type Task,type Deal,type History,type Note,type Audit} from '@/lib/domain';
import {Heading,Badge,TaskList,DealList} from '@/components/ui';
import {ActionForm} from '@/components/action-form';
export async function load({params}:{params:Promise<Record<string,string>>;searchParams:Promise<Record<string,string>>}){
 const {section,id}=await params;if(!isSection(section))notFound();try{uuid(id);}catch{notFound();}const {db,organizationId}=await tenant();
 const {data:row,error}=await db.from(section).select('*').eq('id',id).eq('organization_id',organizationId).maybeSingle();if(error)throw new Error('Eintrag konnte nicht geladen werden.');if(!row)notFound();
 const title=section==='customers'?`${row.first_name} ${row.last_name}`:String(row.title);const customerId=section==='customers'?id:row.customer_id;
 const tasksResult=section!=='tasks'?await db.from('tasks').select('*').eq('organization_id',organizationId).eq(section==='customers'?'customer_id':'deal_id',id).order('due_date').limit(50):{data:[],error:null};
 const dealsResult=section==='customers'?await db.from('deals').select('*').eq('organization_id',organizationId).eq('customer_id',id).order('created_at',{ascending:false}).limit(50):{data:[],error:null};
 const historyResult=section==='deals'?await db.from('deal_status_history').select('*').eq('organization_id',organizationId).eq('deal_id',id).order('changed_at',{ascending:false}).limit(100):{data:[],error:null};
 const notesResult=section==='deals'?await db.from('deal_notes').select('*').eq('organization_id',organizationId).eq('deal_id',id).order('created_at',{ascending:false}).limit(50):{data:[],error:null};
 const auditResult=await db.from('audit_logs').select('*').eq('organization_id',organizationId).eq('entity_id',id).order('created_at',{ascending:false}).limit(20);
 if([tasksResult,dealsResult,historyResult,notesResult,auditResult].some(r=>r.error))throw new Error('Aktivitäten konnten nicht geladen werden.');
 const notes=notesResult.data as Note[];const authorIds=[...new Set(notes.map(n=>n.created_by))];const authors=authorIds.length?await db.from('profiles').select('user_id,first_name,last_name').in('user_id',authorIds):{data:[],error:null};if(authors.error)throw new Error('Autoren konnten nicht geladen werden.');
 const customer=customerId&&section!=='customers'?await db.from('customers').select('id,first_name,last_name').eq('id',customerId).eq('organization_id',organizationId).maybeSingle():{data:null,error:null};if(customer.error)throw new Error('Kunde konnte nicht geladen werden.');
 return <><Link className="back-link" href={`/portal/${section}`}>← {sections[section].title}</Link><Heading title={title} eyebrow={section==='deals'?String(row.deal_number):sections[section].singular}><Link className="button" href={`/portal/${section}/edit?id=${id}`}>Bearbeiten</Link></Heading><div className="detail-grid"><section className="panel"><div className="inline"><h2>Details</h2>{section!=='customers'&&<Badge value={row.status}/>}</div><dl className="details">{sections[section].fields.filter(f=>!['textarea','customer','deal','member'].includes(f.type??'')).map(f=><div key={f.name}><dt>{f.label}</dt><dd>{f.name==='investment_amount'?money(row[f.name]):f.type==='date'?formatDate(row[f.name]):labels[row[f.name]]??row[f.name]??'—'}</dd></div>)}<div><dt>Erstellt am</dt><dd>{formatDate(row.created_at)}</dd></div><div><dt>Zuletzt geändert</dt><dd>{formatDate(row.updated_at)}</dd></div>{customer.data&&<div><dt>Kunde</dt><dd><Link href={`/portal/customers/detail?id=${customer.data.id}`}>{customer.data.first_name} {customer.data.last_name}</Link></dd></div>}{section==='tasks'&&row.deal_id&&<div><dt>Vermittlung</dt><dd><Link href={`/portal/deals/detail?id=${row.deal_id}`}>Vorgang öffnen →</Link></dd></div>}</dl><h3>{section==='tasks'?'Beschreibung':'Interne Notizen'}</h3><p className="pre-wrap">{row.internal_notes??row.description??'Keine Notizen hinterlegt.'}</p></section><aside className="panel"><h2>Nächster Schritt</h2><div className="quick-actions vertical">{section==='customers'&&<Link href={`/portal/deals/new?customer_id=${id}`}>+ Neue Vermittlung</Link>}{section!=='tasks'&&<Link href={`/portal/tasks/new?${new URLSearchParams({...(customerId?{customer_id:customerId}:{}),...(section==='deals'?{deal_id:id}:{})})}`}>+ Wiedervorlage</Link>}{section==='tasks'&&row.status!=='completed'&&row.status!=='cancelled'&&<ActionForm action={completeTask.bind(null,id)} label="Als erledigt markieren"/>}</div><h3>Aktivität</h3><ul className="timeline">{(auditResult.data as Audit[]).map(a=><li key={a.id}><strong>{a.action.replaceAll('_',' ')}</strong><small>{formatDate(a.created_at)}</small></li>)}</ul><small>Die letzten 20 Ereignisse.</small></aside></div>
 {section==='customers'&&<section className="panel"><h2>Vermittlungen</h2><DealList deals={dealsResult.data as Deal[]}/><small>Bis zu 50 aktuelle Vorgänge.</small></section>}
 {section!=='tasks'&&<section className="panel"><h2>Verknüpfte Aufgaben</h2><TaskList tasks={tasksResult.data as Task[]}/><small>Bis zu 50 Aufgaben nach Fälligkeit.</small></section>}
 {section==='deals'&&<div className="dashboard-grid"><section className="panel"><h2>Status-Timeline</h2><ul className="timeline">{(historyResult.data as History[]).map(h=><li key={h.id}><strong>{h.old_status?`${labels[h.old_status]} → `:''}{labels[h.new_status]}</strong><small>{formatDate(h.changed_at)}</small></li>)}</ul><small>Die letzten 100 Statusereignisse.</small></section><section className="panel"><h2>Interne Notizen</h2>{notes.map(n=><article className="note" key={n.id}><small>{(()=>{const author=authors.data?.find(p=>p.user_id===n.created_by);return author?`${author.first_name} ${author.last_name}`:'Teammitglied';})()} · {formatDate(n.created_at)}</small><p className="pre-wrap">{n.content}</p></article>)}<ActionForm action={addNote.bind(null,id)} label="Notiz hinzufügen"><label>Neue Notiz<textarea name="content" rows={3} required maxLength={5000}/></label></ActionForm><small>Die letzten 50 Notizen.</small></section></div>}</>;
}
