import { pageMetadata } from '../company';
export const metadata = pageMetadata('/ratgeber/','Wissen für Finanzanlagenvermittler | Nexus Network','Verständlicher Überblick zu § 34f GewO, IHK-Sachkunde, Erlaubnis, Vermittlerregister, Berufshaftpflicht und FinVermV.');

const external = { target: '_blank', rel: 'noopener noreferrer' } as const;

export default function Page() {
  return <main className="landing knowledge-hub">
    <p className="eyebrow"><span/> Wissen für Finanzprofis</p>
    <h1>Orientierung für Finanzanlagenvermittler.</h1>
    <p className="lead">Wer bestimmte Finanzanlagen gewerblich vermittelt oder dazu berät, arbeitet in einem klar geregelten Rahmen. Dieser Überblick erklärt wichtige Begriffe. Er führt direkt zu den offiziellen Quellen. Die Hinweise ersetzen keine Rechtsberatung und keine Prüfung des Einzelfalls.</p>
    <nav className="knowledge-index" aria-label="Themenübersicht"><a href="#erlaubnis">Erlaubnis nach § 34f</a><a href="#sachkunde">IHK-Sachkunde</a><a href="#qualifikationen">Anerkannte Qualifikationen</a><a href="#register">Vermittlerregister</a><a href="#versicherung">Berufshaftpflicht</a><a href="#pflichten">Berufspflichten</a></nav>
    <div className="knowledge-grid">
      <section id="erlaubnis"><p className="knowledge-number">01 · Berufszugang</p><h2>Erlaubnis nach § 34f GewO</h2><p>Für die in § 34f GewO genannten Tätigkeiten ist grundsätzlich eine Erlaubnis nötig. Das betrifft die gewerbliche Vermittlung bestimmter Finanzanlagen und die Beratung dazu. Der mögliche Umfang richtet sich nach den beantragten Produktgruppen. Wichtige Voraussetzungen sind Zuverlässigkeit, geordnete Finanzen, Berufshaftpflicht und Sachkunde.</p><a className="source-link" href="https://www.gesetze-im-internet.de/gewo/__34f.html" {...external}>§ 34f GewO beim Bundesministerium der Justiz <span>↗</span></a></section>
      <section id="sachkunde"><p className="knowledge-number">02 · Prüfung</p><h2>Sachkundenachweis und IHK-Prüfung</h2><p>Viele Vermittler weisen ihre Sachkunde mit der IHK-Prüfung nach. Sie heißt „Geprüfter Finanzanlagenfachmann“ oder „Geprüfte Finanzanlagenfachfrau IHK“. Die Prüfung behandelt fachliche und rechtliche Grundlagen sowie die Kundenberatung. Termine, Anmeldung und Prüfungsort richten sich nach der zuständigen Kammer.</p><a className="source-link" href="https://www.ihk.de/berlin/pruefungen-lehrgaenge/pruefungen/sach-und-fachkundepruefung/finanzanlagenvermittler-3890084" {...external}>Offizielle Informationen zur IHK-Sachkundeprüfung <span>↗</span></a></section>
      <section id="qualifikationen"><p className="knowledge-number">03 · Alternativen</p><h2>Gleichgestellte Berufsqualifikationen</h2><p>Nicht jeder Antragsteller muss dieselbe IHK-Prüfung ablegen. Bestimmte Abschlüsse können als Nachweis der Sachkunde gelten. Bei manchen Abschlüssen ist auch Berufserfahrung nötig. Entscheidend sind die gesetzlichen Regeln und die Prüfung durch die zuständige Behörde. Eine pauschale Aussage der Website reicht dafür nicht aus.</p><a className="source-link" href="https://www.gesetze-im-internet.de/finvermv/__4.html" {...external}>§ 4 FinVermV zu gleichgestellten Qualifikationen <span>↗</span></a></section>
      <section id="register"><p className="knowledge-number">04 · Transparenz</p><h2>Eintragung im Vermittlerregister</h2><p>Finanzanlagenvermittler stehen mit ihren beruflichen Daten im öffentlichen Vermittlerregister. Die Industrie- und Handelskammern führen dieses Register über eine gemeinsame Stelle. Kunden und Marktteilnehmer können dort die Zulassung prüfen. Auch der Umfang der registrierten Tätigkeit ist einsehbar.</p><a className="source-link" href="https://www.vermittlerregister.info/vermittler" {...external}>Offizielles Vermittlerregister und Erläuterungen <span>↗</span></a></section>
      <section id="versicherung"><p className="knowledge-number">05 · Absicherung</p><h2>Berufshaftpflichtversicherung</h2><p>Eine passende Berufshaftpflicht ist eine Voraussetzung für die Erlaubnis. Sie soll Schäden am Vermögen abdecken, die durch die berufliche Tätigkeit entstehen. Die nötige Deckung und die aktuellen Mindestbeträge ergeben sich aus dem geltenden Recht. Einzelheiten sollten Vermittler mit der zuständigen Stelle klären.</p><a className="source-link" href="https://www.gesetze-im-internet.de/finvermv/__9.html" {...external}>§ 9 FinVermV zur Versicherungspflicht <span>↗</span></a></section>
      <section id="pflichten"><p className="knowledge-number">06 · Berufspraxis</p><h2>Information, Beratung und Dokumentation</h2><p>Die FinVermV nennt wichtige Pflichten für die tägliche Arbeit. Dazu gehören Angaben über Status und Vergütung. Hinzu kommen Regeln für Beratung, Geeignetheit und Dokumentation. Welche Vorgaben im Einzelfall gelten, hängt von der Tätigkeit, dem Produkt und der Situation des Kunden ab.</p><a className="source-link" href="https://www.gesetze-im-internet.de/finvermv/" {...external}>Vollständige Finanzanlagenvermittlungsverordnung <span>↗</span></a></section>
    </div>
    <aside className="knowledge-note"><h2>Was Nexus Network dabei leistet</h2><p>Im persönlichen Gespräch klären wir die wichtigen fachlichen und organisatorischen Fragen zur Zusammenarbeit. Über Erlaubnis, Anerkennung einer Qualifikation und Registrierung entscheiden die zuständigen Stellen.</p><a className="button primary" href="/#kontakt">Persönliches Gespräch anfragen <span>↗</span></a></aside>
    <a className="text-link back-link" href="/">← Zurück zur Startseite</a>
  </main>;
}
