export const metadata = {
  alternates: { canonical: '/ratgeber/' },
  title: 'Wissen für Finanzanlagenvermittler | Nexus Network',
  description: 'Verständlicher Überblick zu § 34f GewO, IHK-Sachkunde, Erlaubnis, Vermittlerregister, Berufshaftpflicht und FinVermV.',
};

const external = { target: '_blank', rel: 'noopener noreferrer' } as const;

export default function Page() {
  return <main className="landing knowledge-hub">
    <p className="eyebrow"><span/> Wissen für Finanzprofis</p>
    <h1>Orientierung für Finanzanlagenvermittler.</h1>
    <p className="lead">Wer gewerbsmäßig bestimmte Finanzanlagen vermittelt oder dazu berät, bewegt sich in einem klar geregelten beruflichen Rahmen. Dieser Überblick ordnet wichtige Begriffe ein und führt direkt zu den offiziellen Informationsquellen. Er ersetzt keine Rechtsberatung und keine Prüfung des Einzelfalls.</p>
    <nav className="knowledge-index" aria-label="Themenübersicht"><a href="#erlaubnis">Erlaubnis nach § 34f</a><a href="#sachkunde">IHK-Sachkunde</a><a href="#qualifikationen">Anerkannte Qualifikationen</a><a href="#register">Vermittlerregister</a><a href="#versicherung">Berufshaftpflicht</a><a href="#pflichten">Berufspflichten</a></nav>
    <div className="knowledge-grid">
      <section id="erlaubnis"><p className="knowledge-number">01 · Berufszugang</p><h2>Erlaubnis nach § 34f GewO</h2><p>Für die gewerbsmäßige Anlagevermittlung oder Anlageberatung zu den in § 34f GewO genannten Finanzanlagen ist grundsätzlich eine Erlaubnis der zuständigen Behörde erforderlich. Der mögliche Umfang richtet sich nach den beantragten Produktkategorien. Zu den gesetzlichen Voraussetzungen gehören insbesondere persönliche Zuverlässigkeit, geordnete Vermögensverhältnisse, Berufshaftpflichtversicherung und Sachkunde.</p><a className="source-link" href="https://www.gesetze-im-internet.de/gewo/__34f.html" {...external}>§ 34f GewO beim Bundesministerium der Justiz <span>↗</span></a></section>
      <section id="sachkunde"><p className="knowledge-number">02 · Prüfung</p><h2>Sachkundenachweis und IHK-Prüfung</h2><p>Die erforderliche Sachkunde wird häufig über die Prüfung „Geprüfter Finanzanlagenfachmann/Geprüfte Finanzanlagenfachfrau IHK“ nachgewiesen. Die Prüfung umfasst fachliche und rechtliche Grundlagen sowie Kenntnisse zur Kundenberatung. Welche IHK Prüfungen anbietet, welche Termine gelten und wie die Anmeldung funktioniert, hängt von der zuständigen Kammer ab.</p><a className="source-link" href="https://www.ihk.de/berlin/pruefungen-lehrgaenge/pruefungen/sach-und-fachkundepruefung/finanzanlagenvermittler-3890084" {...external}>Offizielle Informationen zur IHK-Sachkundeprüfung <span>↗</span></a></section>
      <section id="qualifikationen"><p className="knowledge-number">03 · Alternativen</p><h2>Gleichgestellte Berufsqualifikationen</h2><p>Nicht jeder Antragsteller muss zwingend dieselbe IHK-Prüfung ablegen. Bestimmte bereits erworbene Berufsqualifikationen können dem Sachkundenachweis gleichgestellt sein; je nach Abschluss kann zusätzliche Berufserfahrung erforderlich werden. Maßgeblich sind die gesetzlichen Regelungen und die Bewertung der zuständigen Erlaubnisbehörde, nicht eine pauschale Aussage auf einer Unternehmenswebsite.</p><a className="source-link" href="https://www.gesetze-im-internet.de/finvermv/__4.html" {...external}>§ 4 FinVermV zu gleichgestellten Qualifikationen <span>↗</span></a></section>
      <section id="register"><p className="knowledge-number">04 · Transparenz</p><h2>Eintragung im Vermittlerregister</h2><p>Finanzanlagenvermittler werden mit ihren gewerbebezogenen Daten im öffentlichen Vermittlerregister geführt. Das Register wird von den Industrie- und Handelskammern über eine gemeinsame Stelle der Deutschen Industrie- und Handelskammer betrieben. Es ermöglicht insbesondere Kunden und Marktteilnehmern, Zulassung und Umfang einer registrierten Tätigkeit zu überprüfen.</p><a className="source-link" href="https://www.vermittlerregister.info/vermittler" {...external}>Offizielles Vermittlerregister und Erläuterungen <span>↗</span></a></section>
      <section id="versicherung"><p className="knowledge-number">05 · Absicherung</p><h2>Berufshaftpflichtversicherung</h2><p>Der Nachweis einer den gesetzlichen Vorgaben entsprechenden Berufshaftpflichtversicherung gehört zu den Voraussetzungen der Erlaubnis. Sie soll Vermögensschäden aus der beruflichen Tätigkeit abdecken. Die konkret erforderliche Ausgestaltung und die jeweils geltenden Mindestversicherungssummen sollten anhand der aktuellen Rechtslage und mit der zuständigen Stelle geklärt werden.</p><a className="source-link" href="https://www.gesetze-im-internet.de/finvermv/__9.html" {...external}>§ 9 FinVermV zur Versicherungspflicht <span>↗</span></a></section>
      <section id="pflichten"><p className="knowledge-number">06 · Berufspraxis</p><h2>Informations-, Beratungs- und Dokumentationspflichten</h2><p>Die Finanzanlagenvermittlungsverordnung konkretisiert Pflichten für die berufliche Praxis. Dazu zählen unter anderem Informationen über Status und Vergütung, Anforderungen an Beratung und Geeignetheit sowie Dokumentations- und Aufzeichnungspflichten. Welche Vorgaben im konkreten Fall greifen, hängt von Tätigkeit, Produktkategorie und Kundensituation ab.</p><a className="source-link" href="https://www.gesetze-im-internet.de/finvermv/" {...external}>Vollständige Finanzanlagenvermittlungsverordnung <span>↗</span></a></section>
    </div>
    <aside className="knowledge-note"><h2>Was Nexus Network dabei leistet</h2><p>Wir ordnen im persönlichen Austausch ein, welche fachlichen und organisatorischen Voraussetzungen für die angestrebte Zusammenarbeit relevant sind. Die Entscheidung über Erlaubnis, Anerkennung einer Qualifikation oder Registrierung liegt bei den jeweils zuständigen Stellen.</p><a className="button primary" href="/#kontakt">Persönliches Gespräch anfragen <span>↗</span></a></aside>
    <a className="text-link back-link" href="/">← Zurück zur Startseite</a>
  </main>;
}
