const links = [['Leistungen', '#zusammenarbeit'], ['Für Finanzprofis', '#zielgruppen'], ['Warum Nexus Network', '#vorteile'], ['FAQ', '#faq']];
import { ContactForm } from './contact-form';
import { NetworkField } from './network-field';
import { MobileNavigation } from './mobile-navigation';
import Image from 'next/image';

function BrandLogo({ priority = false }: { priority?: boolean }) {
  return <span className="brand-logo-frame"><Image className="brand-logo" src="/nexus-brand.png" width={740} height={349} alt="Logo von Nexus Network" priority={priority} /></span>;
}

export default function Home() {
  return <>
    <header className="site-header">
      <a className="brand" href="#top" aria-label="Nexus Network – zur Startseite"><BrandLogo priority /><span className="brand-words"><span className="brand-name">NEXUS</span><span className="brand-subname">NETWORK</span></span></a>
      <nav aria-label="Hauptnavigation">{links.map(([label, href]) => <a href={href} key={href}>{label}</a>)}</nav>
      <a className="header-cta" href="#kontakt" aria-label="Kontakt aufnehmen"><span className="header-cta-text">Kontakt<span className="cta-label"> aufnehmen</span></span><span className="header-cta-arrow" aria-hidden="true"><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17 17 7M7 7h10v10"/></svg></span></a>
      <MobileNavigation links={links}/>
    </header>
    <main id="top">
      <section className="hero">
        <NetworkField/>
        <div className="hero-copy">
          <p className="eyebrow"><span/> Verbindung. Struktur. Perspektive.</p>
          <h1>Die Verbindung zwischen <em>Finanzfachkräften</em> und Möglichkeiten.</h1>
          <p className="lead">Nexus Network ist die professionelle Anbindungsstelle für Finanzanlagefachkräfte. Wir schaffen die Verbindung zwischen Menschen, Kompetenzen und Möglichkeiten für eine nachhaltig ausgerichtete Zusammenarbeit.</p>
          <div className="hero-actions"><a className="button primary" href="#kontakt">Kontakt aufnehmen <span>→</span></a><a className="button secondary" href="#zielgruppen">Mehr erfahren <span>↓</span></a></div>
          <div className="trust-row"><div><strong>Persönlich</strong><span>Direkte Ansprechpartner</span></div><div><strong>Professionell</strong><span>Klare Prozesse</span></div><div><strong>Partnerschaftlich</strong><span>Auf Augenhöhe</span></div></div>
        </div>
        <div className="hero-orbit" aria-hidden="true"><span/><span/><span/></div>
      </section>
      <section className="intro section" id="zielgruppen">
        <div><p className="eyebrow"><span/> Nexus Network im Überblick</p><h2>Eine professionelle Struktur für Menschen, die Finanzberatung eigenständig gestalten.</h2></div>
        <div><p>Nexus Network richtet sich an Finanzanlagefachkräfte, selbstständige Finanzberater und Finanzanlagenvermittler, die eine verlässliche Anbindung und eine klare Zusammenarbeit suchen.</p><p>Im Mittelpunkt steht keine kurzfristige Vermittlung, sondern eine tragfähige geschäftliche Verbindung: persönlich, transparent und mit Raum für die individuelle Entwicklung.</p><a className="text-link" href="/finanzberater-anbindung">Mehr zur Finanzberater-Anbindung <span>→</span></a></div>
      </section>
      <section className="dark-section" id="zusammenarbeit">
        <div className="section-heading"><p className="eyebrow"><span/> So funktioniert die Zusammenarbeit</p><h2>Vom ersten Gespräch zur passenden Verbindung.</h2><p>Wir lernen Ihre Ausgangssituation kennen, klären Erwartungen und prüfen gemeinsam, ob Nexus Network zu Ihrem beruflichen Weg passt.</p></div>
        <div className="steps">{[['01','Kennenlernen','Ihre Tätigkeit, Ziele und Anforderungen stehen am Anfang.'],['02','Einordnung','Wir besprechen transparent, welche Form der Zusammenarbeit sinnvoll ist.'],['03','Anbindung','Bei gegenseitiger Passung gestalten wir die nächsten Schritte strukturiert.'],['04','Begleitung','Ein direkter Austausch bleibt auch nach dem Start selbstverständlich.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div>
      </section>
      <section className="section benefits" id="vorteile">
        <div className="section-heading"><p className="eyebrow"><span/> Warum Nexus Network</p><h2>Verbindung braucht Klarheit, Vertrauen und Substanz.</h2></div>
        <div className="cards">{[['Direkte Kommunikation','Sie sprechen mit Menschen, die Ihre Fragen einordnen und Entscheidungen nachvollziehbar machen.'],['Professionelle Abläufe','Klare Zuständigkeiten und strukturierte Prozesse schaffen eine verlässliche Arbeitsgrundlage.'],['Individuelle Perspektive','Ihre Situation wird nicht in ein Standardschema gepresst. Wir betrachten, was fachlich und unternehmerisch passt.'],['Langfristige Ausrichtung','Die Zusammenarbeit ist auf Kontinuität ausgelegt – ohne kurzfristige Versprechen oder unrealistische Aussagen.']].map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div>
      </section>
      <section className="section audience">
        <div><p className="eyebrow"><span/> Für wen wir da sind</p><h2>Eine Anlaufstelle für erfahrene und angehende Finanzprofis.</h2></div>
        <div className="audience-links"><a href="/finanzberater-anbindung"><strong>Selbstständige Finanzberater</strong><span>Professionelle Anbindung und unternehmerische Perspektive →</span></a><a href="/finanzanlagenvermittler"><strong>Finanzanlagenvermittler</strong><span>Strukturierte Zusammenarbeit für die Vermittlungstätigkeit →</span></a></div>
      </section>
      <section className="section profile" aria-labelledby="profil-heading">
        <div className="section-heading"><p className="eyebrow"><span/> Zusammenarbeit mit Substanz</p><h2 id="profil-heading">Was eine professionelle Anbindung im Alltag auszeichnet.</h2></div>
        <div className="profile-copy">
          <div><p>Eine gute geschäftliche Verbindung beginnt mit einem klaren Verständnis der jeweiligen Ausgangssituation. Deshalb betrachten wir nicht nur einzelne Leistungen, sondern auch Arbeitsweise, Ziele und unternehmerische Perspektive. Finanzfachkräfte erhalten bei Nexus Network einen direkten Ansprechpartner und nachvollziehbare nächste Schritte. Fragen werden offen eingeordnet, Zuständigkeiten transparent benannt und Vereinbarungen verständlich besprochen.</p><p>Die Möglichkeiten einer Zusammenarbeit hängen von den persönlichen und fachlichen Voraussetzungen ab. Statt pauschaler Lösungen steht eine individuelle Prüfung im Mittelpunkt. So entsteht eine Struktur, die zur eigenen Tätigkeit passen kann und zugleich Raum für Entwicklung lässt. Dabei bleiben regulatorische Anforderungen, Verantwortung gegenüber Kunden und eine professionelle Dokumentation feste Bestandteile des Arbeitsalltags.</p><p>Im ersten Austausch geht es daher nicht um einen schnellen Abschluss. Entscheidend ist, ob Erwartungen, Arbeitsweise und Rahmenbedingungen zusammenpassen. Finanzprofis können ihre Fragen konkret einbringen und erhalten eine ehrliche Einordnung der nächsten Schritte. Das schafft Orientierung, bevor weitere Entscheidungen getroffen werden. Auch im laufenden Kontakt bleiben Veränderungen besprechbar, denn eine tragfähige Anbindung muss sich an nachvollziehbaren Anforderungen und der tatsächlichen beruflichen Praxis messen lassen.</p></div>
          <div><p>Nexus Network versteht sich als Schnittstelle für selbstständige Finanzberater, Finanzanlagenvermittler und weitere Finanzanlagefachkräfte. Unser Ziel ist eine verlässliche, langfristig gedachte Zusammenarbeit auf Augenhöhe. Dazu gehören kurze Kommunikationswege, realistische Aussagen und ein gemeinsames Verständnis davon, wie Qualität im Tagesgeschäft dauerhaft gelebt wird.</p><p>Eine Zusammenarbeit soll den beruflichen Alltag übersichtlicher machen. Dazu zählt, Informationen rechtzeitig bereitzustellen, Rückfragen eindeutig zuzuordnen und Entscheidungen verständlich zu dokumentieren. Wer als Finanzanlagevermittler eigenständig arbeitet, braucht keine lauten Versprechen, sondern belastbare Orientierung. Nexus Network verbindet deshalb persönliche Erreichbarkeit mit strukturierten Abläufen. Die konkrete Ausgestaltung wird gemeinsam besprochen und richtet sich nach Tätigkeit, Erfahrung und den jeweils geltenden Voraussetzungen. So bleiben Verantwortlichkeiten klar, während neue Möglichkeiten sachlich geprüft werden können.</p><p>Das Unternehmen wird zu gleichen Teilen von <a href="https://www.investsmartstrategie.solutions/" target="_blank" rel="noopener noreferrer">NEXUS Finanz GmbH &amp; Co. KG</a> und Diren Bulut getragen. Diese Verbindung bündelt fachliche Erfahrung und unternehmerische Perspektive. Sie ersetzt keine individuelle Prüfung, schafft aber einen klaren Rahmen für den persönlichen Austausch und die gemeinsame Einordnung passender Möglichkeiten.</p></div>
        </div>
        <aside className="orientation" aria-label="Fachliche Orientierung"><p><span>Fachliche Orientierung</span> Verbindliche Grundlagen für Finanzanlagenvermittler regelt insbesondere <a href="https://www.gesetze-im-internet.de/gewo/__34f.html" target="_blank" rel="noopener noreferrer">§ 34f der Gewerbeordnung</a>. Ergänzend beschreibt die <a href="https://www.gesetze-im-internet.de/finvermv/" target="_blank" rel="noopener noreferrer">Finanzanlagenvermittlungsverordnung</a> zentrale Berufspflichten. Diese externen Quellen dienen der allgemeinen Information und ersetzen keine Rechtsberatung.</p></aside>
      </section>
      <section className="faq section" id="faq"><div className="section-heading"><p className="eyebrow"><span/> Häufige Fragen</p><h2>Was Finanzfachkräfte vor dem ersten Gespräch wissen möchten.</h2></div><div className="faq-list">{[['An wen richtet sich Nexus Network?','An selbstständige Finanzberater, Finanzanlagenvermittler und weitere Finanzanlagefachkräfte, die eine professionelle geschäftliche Anbindung suchen.'],['Wie beginnt eine Zusammenarbeit?','Mit einem unverbindlichen Kennenlerngespräch. Dabei klären wir Ihre aktuelle Situation, Ihre Ziele und die gegenseitigen Erwartungen.'],['Was bedeutet professionelle Anbindung bei Nexus Network?','Professionelle Anbindung bedeutet für uns: feste Ansprechpartner, klar benannte Abläufe und eine Zusammenarbeit, die zur tatsächlichen beruflichen Situation passt. Welche konkreten Möglichkeiten infrage kommen, wird nicht pauschal auf der Website versprochen, sondern im persönlichen Austausch nachvollziehbar geklärt.'],['Ist das erste Gespräch bereits verbindlich?','Nein. Das Kennenlernen dient zunächst der gegenseitigen Einordnung. Sie können Ihre Arbeitsweise, Ziele und offenen Fragen schildern. Gemeinsam besprechen wir, ob die grundlegenden Erwartungen zusammenpassen und welche Informationen für eine fundierte Entscheidung noch benötigt werden. Erst danach werden mögliche weitere Schritte abgestimmt.'],['Verspricht Nexus Network bestimmte Erträge?','Nein. Nexus Network macht keine Gewinn- oder Erfolgsversprechen. Im Mittelpunkt stehen eine professionelle Struktur und eine nachvollziehbare Zusammenarbeit.'],['Welche Voraussetzungen gelten?','Die konkreten fachlichen, gewerberechtlichen und organisatorischen Voraussetzungen werden individuell und transparent im Gespräch geklärt.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
      <section className="contact section" id="kontakt"><div><p className="eyebrow"><span/> Kontakt</p><h2>Lassen Sie uns herausfinden, ob wir zueinander passen.</h2><p>Schildern Sie uns kurz Ihre Situation. Wir melden uns persönlich und ohne unverbindliche Werbeversprechen bei Ihnen.</p><p className="direct">Direkter Kontakt<br/><a href="mailto:hello@nexusnetwork.pro">hello@nexusnetwork.pro</a></p><div className="contact-addresses"><p>Anbindung<br/><a href="mailto:anbindung@nexusnetwork.pro">anbindung@nexusnetwork.pro</a></p><p>Kooperation<br/><a href="mailto:kooperation@nexusnetwork.pro">kooperation@nexusnetwork.pro</a></p><p>Fragen<br/><a href="mailto:frage@nexusnetwork.pro">frage@nexusnetwork.pro</a></p></div></div><ContactForm/></section>
    </main>
    <footer><div className="brand"><BrandLogo /><span className="brand-words"><span className="brand-name">NEXUS</span><span className="brand-subname">NETWORK</span></span></div><p>Professionelle Verbindungen für Finanzanlagefachkräfte.</p><nav className="footer-links" aria-label="Rechtliches und Wissen"><a href="/impressum/">Impressum</a><a href="/datenschutz/">Datenschutz</a><a href="/ratgeber/">Ratgeber</a></nav><nav className="social-sharing" aria-label="Nexus Network teilen"><span>Seite teilen</span><a href="https://www.linkedin.com/sharing/share-offsite/?url=https%3A%2F%2Fnexusnetwork.pro%2F" target="_blank" rel="noopener noreferrer" aria-label="Nexus Network auf LinkedIn teilen">LinkedIn</a><a href="https://twitter.com/intent/tweet?url=https%3A%2F%2Fnexusnetwork.pro%2F&amp;text=Nexus%20Network" target="_blank" rel="noopener noreferrer" aria-label="Nexus Network auf X teilen">X</a><a href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fnexusnetwork.pro%2F" target="_blank" rel="noopener noreferrer" aria-label="Nexus Network auf Facebook teilen">Facebook</a><a href="https://wa.me/?text=Nexus%20Network%20https%3A%2F%2Fnexusnetwork.pro%2F" target="_blank" rel="noopener noreferrer" aria-label="Nexus Network über WhatsApp teilen">WhatsApp</a><a href="mailto:?subject=Nexus%20Network&amp;body=https%3A%2F%2Fnexusnetwork.pro%2F" aria-label="Nexus Network per E-Mail teilen">E-Mail</a></nav><small>© {new Date().getFullYear()} Nexus Network. Alle Rechte vorbehalten.</small></footer>
  </>;
}
