import Link from 'next/link';
import {notFound} from 'next/navigation';
import {admin} from '@/lib/access';
import {uuid} from '@/lib/validation';
import {review} from '@/lib/actions';
import {labels,formatDate,type Audit} from '@/lib/domain';
import {onboardingFields} from '@/lib/fields';
import {Heading,Badge} from '@/components/ui';
import {ActionForm} from '@/components/action-form';
export default async function Page({params}:{params:Promise<{id:string}>}){const {id}=await params;try{uuid(id);}catch{notFound();}const {db}=await admin();const [profile,partner,audit]=await Promise.all([db.from('profiles').select('*').eq('user_id',id).eq('role','partner').maybeSingle(),db.from('partner_profiles').select('*').eq('user_id',id).maybeSingle(),db.from('audit_logs').select('*').eq('entity_id',id).order('created_at',{ascending:false}).limit(100)]);if([profile,partner,audit].some(r=>r.error))throw new Error('Partner konnte nicht geladen werden.');if(!profile.data||!partner.data)notFound();const values={...partner.data,...profile.data};return <><Link href="/admin">← Alle Partner</Link><Heading title={`${profile.data.first_name} ${profile.data.last_name}`}><Badge value={profile.data.status}/></Heading><div className="detail-grid"><section className="panel"><h2>Angaben zur Prüfung</h2><dl className="details">{onboardingFields.map(f=><div key={f.name}><dt>{f.label}</dt><dd>{values[f.name]||'—'}</dd></div>)}<div><dt>Eingereicht</dt><dd>{formatDate(partner.data.submitted_at)}</dd></div></dl><p className="muted">Die Angaben sind Selbstauskünfte und stellen keinen automatischen Berechtigungsnachweis dar.</p></section><section className="panel"><h2>Entscheidung</h2><ActionForm action={review.bind(null,id)} label="Status verbindlich ändern"><label>Neuer Status<select name="status" defaultValue={profile.data.status==='pending'?'under_review':profile.data.status}>{['under_review','active','suspended','rejected'].map(s=><option value={s} key={s} disabled={s==='active'&&!partner.data.submitted_at}>{labels[s]}</option>)}</select></label><p className="muted">Jede Änderung wird automatisch protokolliert. Freigabe erst nach eingereichtem Onboarding.</p></ActionForm><h3>Prüfverlauf</h3><ul className="timeline">{(audit.data as Audit[]).map(a=><li key={a.id}><strong>{a.action.replaceAll('_',' ')}</strong><small>{formatDate(a.created_at)}</small></li>)}</ul></section></div></>;}
